name: Linters

on: pull_request

env:
  FORCE_COLOR: 1

jobs:
    eslint:
        runs-on: ubuntu-22.04

        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Setup Node.js
            uses: actions/setup-node@v2
            with:
              node-version: "16" # Adjust Node.js version as needed

          - name: Install Dependencies
            run: |
              npm install --save-dev eslint@7 eslint-config-airbnb@18 eslint-plugin-import@2 eslint-plugin-jsx-a11y@6 eslint-plugin-react@7 eslint-plugin-react-hooks@4 @typescript-eslint/eslint-plugin@latest @typescript-eslint/parser@latest
              [ -f .eslintrc.js ] || wget https://raw.githubusercontent.com/microverseinc/linters-config/master/react-redux/.eslintrc.js
              [ -f .babelrc ] || wget https://raw.githubusercontent.com/microverseinc/linters-config/master/react-redux/.babelrc

          - name: Run ESLint
            run: npx eslint "**/*.{ts,tsx}" --fix --ext .ts,.tsx

          - name: ESLint Report
            run: npx eslint "**/*.{ts,tsx}" --format stylish --ext .ts,.tsx
    nodechecker:
        name: node_modules checker
        runs-on: ubuntu-22.04
        steps:
          - uses: actions/checkout@v3
          - name: Check node_modules existence
            run: |
              if [ -d "node_modules/" ]; then echo -e "\e[1;31mThe node_modules/ folder was pushed to the repo. Please remove it from the GitHub repository and try again."; echo -e "\e[1;32mYou can set up a .gitignore file with this folder included on it to prevent this from happening in the future." && exit 1; fi
